//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigMoscow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigMoscow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business owner.
        /// </summary>
        public static string business_owner {
            get {
                return ResourceManager.GetString("business_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string button_next {
            get {
                return ResourceManager.GetString("button_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string button_previous {
            get {
                return ResourceManager.GetString("button_previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string button_send_smth {
            get {
                return ResourceManager.GetString("button_send_smth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display category.
        /// </summary>
        public static string Display_category {
            get {
                return ResourceManager.GetString("Display_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear visitor!
        ///
        ///Allow us to introduce BIGMOSCOW (Business Investment Guide to Moscow), a multimedia magazine available for you to download for free on the App Store and Google Play.
        ///
        ///BIGMOSCOW features:
        ///- objective information about the economy and promising segments of Moscow market,
        ///- success stories from foreign entrepreneurs, who have been working in Moscow,
        ///- current business and cultural events, and the Moscow expat community news,
        ///- expert consultations about various practical business aspects [rest of string was truncated]&quot;;.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the internet connection and email adress.
        /// </summary>
        public static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal State.
        /// </summary>
        public static string Federal_State {
            get {
                return ResourceManager.GetString("Federal_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you are trying to send on email is not found.
        /// </summary>
        public static string filenotfound {
            get {
                return ResourceManager.GetString("filenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German Chamber of Commerce.
        /// </summary>
        public static string German_Chamber_of_Commerce {
            get {
                return ResourceManager.GetString("German_Chamber_of_Commerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired manager.
        /// </summary>
        public static string hired_manager {
            get {
                return ResourceManager.GetString("hired_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investor.
        /// </summary>
        public static string Investor {
            get {
                return ResourceManager.GetString("Investor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region with the good prospects.
        /// </summary>
        public static string m1_1 {
            get {
                return ResourceManager.GetString("m1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m1_2 {
            get {
                return ResourceManager.GetString("m1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m1_3 {
            get {
                return ResourceManager.GetString("m1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m1_4 {
            get {
                return ResourceManager.GetString("m1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m1_5 {
            get {
                return ResourceManager.GetString("m1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m1_6 {
            get {
                return ResourceManager.GetString("m1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string m1_7 {
            get {
                return ResourceManager.GetString("m1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m1_8 {
            get {
                return ResourceManager.GetString("m1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m10_1 {
            get {
                return ResourceManager.GetString("m10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m10_10 {
            get {
                return ResourceManager.GetString("m10_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m10_11 {
            get {
                return ResourceManager.GetString("m10_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m10_2 {
            get {
                return ResourceManager.GetString("m10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m10_3 {
            get {
                return ResourceManager.GetString("m10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m10_4 {
            get {
                return ResourceManager.GetString("m10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m10_5 {
            get {
                return ResourceManager.GetString("m10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m10_6 {
            get {
                return ResourceManager.GetString("m10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m10_7 {
            get {
                return ResourceManager.GetString("m10_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m10_8 {
            get {
                return ResourceManager.GetString("m10_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m10_9 {
            get {
                return ResourceManager.GetString("m10_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m11_1 {
            get {
                return ResourceManager.GetString("m11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m11_10 {
            get {
                return ResourceManager.GetString("m11_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m11_11 {
            get {
                return ResourceManager.GetString("m11_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m11_12 {
            get {
                return ResourceManager.GetString("m11_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m11_2 {
            get {
                return ResourceManager.GetString("m11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string m11_3 {
            get {
                return ResourceManager.GetString("m11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m11_4 {
            get {
                return ResourceManager.GetString("m11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m11_5 {
            get {
                return ResourceManager.GetString("m11_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m11_6 {
            get {
                return ResourceManager.GetString("m11_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m11_7 {
            get {
                return ResourceManager.GetString("m11_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m11_8 {
            get {
                return ResourceManager.GetString("m11_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m11_9 {
            get {
                return ResourceManager.GetString("m11_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m12_1 {
            get {
                return ResourceManager.GetString("m12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m12_10 {
            get {
                return ResourceManager.GetString("m12_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m12_11 {
            get {
                return ResourceManager.GetString("m12_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m12_2 {
            get {
                return ResourceManager.GetString("m12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m12_3 {
            get {
                return ResourceManager.GetString("m12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m12_4 {
            get {
                return ResourceManager.GetString("m12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m12_5 {
            get {
                return ResourceManager.GetString("m12_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m12_6 {
            get {
                return ResourceManager.GetString("m12_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m12_7 {
            get {
                return ResourceManager.GetString("m12_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m12_8 {
            get {
                return ResourceManager.GetString("m12_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m12_9 {
            get {
                return ResourceManager.GetString("m12_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m13_1 {
            get {
                return ResourceManager.GetString("m13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m13_10 {
            get {
                return ResourceManager.GetString("m13_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m13_11 {
            get {
                return ResourceManager.GetString("m13_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m13_2 {
            get {
                return ResourceManager.GetString("m13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m13_3 {
            get {
                return ResourceManager.GetString("m13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m13_4 {
            get {
                return ResourceManager.GetString("m13_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m13_5 {
            get {
                return ResourceManager.GetString("m13_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m13_6 {
            get {
                return ResourceManager.GetString("m13_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m13_7 {
            get {
                return ResourceManager.GetString("m13_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m13_8 {
            get {
                return ResourceManager.GetString("m13_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m13_9 {
            get {
                return ResourceManager.GetString("m13_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m14_1 {
            get {
                return ResourceManager.GetString("m14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m14_10 {
            get {
                return ResourceManager.GetString("m14_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m14_11 {
            get {
                return ResourceManager.GetString("m14_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m14_2 {
            get {
                return ResourceManager.GetString("m14_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m14_3 {
            get {
                return ResourceManager.GetString("m14_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m14_4 {
            get {
                return ResourceManager.GetString("m14_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m14_5 {
            get {
                return ResourceManager.GetString("m14_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m14_6 {
            get {
                return ResourceManager.GetString("m14_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m14_7 {
            get {
                return ResourceManager.GetString("m14_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m14_8 {
            get {
                return ResourceManager.GetString("m14_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m14_9 {
            get {
                return ResourceManager.GetString("m14_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m15_1 {
            get {
                return ResourceManager.GetString("m15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m15_10 {
            get {
                return ResourceManager.GetString("m15_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m15_11 {
            get {
                return ResourceManager.GetString("m15_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m15_2 {
            get {
                return ResourceManager.GetString("m15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m15_3 {
            get {
                return ResourceManager.GetString("m15_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m15_4 {
            get {
                return ResourceManager.GetString("m15_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m15_5 {
            get {
                return ResourceManager.GetString("m15_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m15_6 {
            get {
                return ResourceManager.GetString("m15_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m15_7 {
            get {
                return ResourceManager.GetString("m15_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m15_8 {
            get {
                return ResourceManager.GetString("m15_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m15_9 {
            get {
                return ResourceManager.GetString("m15_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От редактора.
        /// </summary>
        public static string m19_1 {
            get {
                return ResourceManager.GetString("m19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макроэкономика.
        /// </summary>
        public static string m19_2 {
            get {
                return ResourceManager.GetString("m19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В фокусе.
        /// </summary>
        public static string m19_3 {
            get {
                return ResourceManager.GetString("m19_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действующие лица.
        /// </summary>
        public static string m19_4 {
            get {
                return ResourceManager.GetString("m19_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобализация.
        /// </summary>
        public static string m19_5 {
            get {
                return ResourceManager.GetString("m19_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образ действия.
        /// </summary>
        public static string m19_6 {
            get {
                return ResourceManager.GetString("m19_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинги.
        /// </summary>
        public static string m19_7 {
            get {
                return ResourceManager.GetString("m19_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образ жизни.
        /// </summary>
        public static string m19_8 {
            get {
                return ResourceManager.GetString("m19_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona grata.
        /// </summary>
        public static string m2_1 {
            get {
                return ResourceManager.GetString("m2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m2_2 {
            get {
                return ResourceManager.GetString("m2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m2_3 {
            get {
                return ResourceManager.GetString("m2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m2_4 {
            get {
                return ResourceManager.GetString("m2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatriots.
        /// </summary>
        public static string m2_5 {
            get {
                return ResourceManager.GetString("m2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m2_6 {
            get {
                return ResourceManager.GetString("m2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibitions.
        /// </summary>
        public static string m2_8 {
            get {
                return ResourceManager.GetString("m2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m3_1 {
            get {
                return ResourceManager.GetString("m3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m3_10 {
            get {
                return ResourceManager.GetString("m3_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m3_2 {
            get {
                return ResourceManager.GetString("m3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work in Moscow.
        /// </summary>
        public static string m3_3 {
            get {
                return ResourceManager.GetString("m3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m3_4 {
            get {
                return ResourceManager.GetString("m3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m3_5 {
            get {
                return ResourceManager.GetString("m3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tendencies.
        /// </summary>
        public static string m3_6 {
            get {
                return ResourceManager.GetString("m3_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m3_7 {
            get {
                return ResourceManager.GetString("m3_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibitions.
        /// </summary>
        public static string m3_8 {
            get {
                return ResourceManager.GetString("m3_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commertial Moscow.
        /// </summary>
        public static string m3_9 {
            get {
                return ResourceManager.GetString("m3_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m4_1 {
            get {
                return ResourceManager.GetString("m4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m4_10 {
            get {
                return ResourceManager.GetString("m4_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life in Moscow.
        /// </summary>
        public static string m4_11 {
            get {
                return ResourceManager.GetString("m4_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m4_2 {
            get {
                return ResourceManager.GetString("m4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m4_3 {
            get {
                return ResourceManager.GetString("m4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m4_4 {
            get {
                return ResourceManager.GetString("m4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m4_5 {
            get {
                return ResourceManager.GetString("m4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m4_6 {
            get {
                return ResourceManager.GetString("m4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m4_7 {
            get {
                return ResourceManager.GetString("m4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m4_8 {
            get {
                return ResourceManager.GetString("m4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m4_9 {
            get {
                return ResourceManager.GetString("m4_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m5_1 {
            get {
                return ResourceManager.GetString("m5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m5_10 {
            get {
                return ResourceManager.GetString("m5_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m5_11 {
            get {
                return ResourceManager.GetString("m5_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m5_2 {
            get {
                return ResourceManager.GetString("m5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To work in Moscow.
        /// </summary>
        public static string m5_3 {
            get {
                return ResourceManager.GetString("m5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m5_4 {
            get {
                return ResourceManager.GetString("m5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m5_5 {
            get {
                return ResourceManager.GetString("m5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m5_6 {
            get {
                return ResourceManager.GetString("m5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m5_7 {
            get {
                return ResourceManager.GetString("m5_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m5_8 {
            get {
                return ResourceManager.GetString("m5_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exhibitions.
        /// </summary>
        public static string m5_9 {
            get {
                return ResourceManager.GetString("m5_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m6_1 {
            get {
                return ResourceManager.GetString("m6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m6_10 {
            get {
                return ResourceManager.GetString("m6_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m6_11 {
            get {
                return ResourceManager.GetString("m6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m6_12 {
            get {
                return ResourceManager.GetString("m6_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m6_2 {
            get {
                return ResourceManager.GetString("m6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m6_3 {
            get {
                return ResourceManager.GetString("m6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m6_4 {
            get {
                return ResourceManager.GetString("m6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m6_5 {
            get {
                return ResourceManager.GetString("m6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m6_6 {
            get {
                return ResourceManager.GetString("m6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m6_7 {
            get {
                return ResourceManager.GetString("m6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m6_8 {
            get {
                return ResourceManager.GetString("m6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportage.
        /// </summary>
        public static string m6_9 {
            get {
                return ResourceManager.GetString("m6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m7_1 {
            get {
                return ResourceManager.GetString("m7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m7_10 {
            get {
                return ResourceManager.GetString("m7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m7_11 {
            get {
                return ResourceManager.GetString("m7_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m7_2 {
            get {
                return ResourceManager.GetString("m7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m7_3 {
            get {
                return ResourceManager.GetString("m7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m7_4 {
            get {
                return ResourceManager.GetString("m7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m7_5 {
            get {
                return ResourceManager.GetString("m7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m7_6 {
            get {
                return ResourceManager.GetString("m7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m7_7 {
            get {
                return ResourceManager.GetString("m7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m7_8 {
            get {
                return ResourceManager.GetString("m7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m7_9 {
            get {
                return ResourceManager.GetString("m7_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m8_1 {
            get {
                return ResourceManager.GetString("m8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m8_10 {
            get {
                return ResourceManager.GetString("m8_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m8_11 {
            get {
                return ResourceManager.GetString("m8_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m8_2 {
            get {
                return ResourceManager.GetString("m8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m8_3 {
            get {
                return ResourceManager.GetString("m8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m8_4 {
            get {
                return ResourceManager.GetString("m8_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m8_5 {
            get {
                return ResourceManager.GetString("m8_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m8_6 {
            get {
                return ResourceManager.GetString("m8_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m8_7 {
            get {
                return ResourceManager.GetString("m8_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m8_8 {
            get {
                return ResourceManager.GetString("m8_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m8_9 {
            get {
                return ResourceManager.GetString("m8_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona.
        /// </summary>
        public static string m9_1 {
            get {
                return ResourceManager.GetString("m9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Moscow.
        /// </summary>
        public static string m9_10 {
            get {
                return ResourceManager.GetString("m9_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living in Moscow.
        /// </summary>
        public static string m9_11 {
            get {
                return ResourceManager.GetString("m9_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Experience.
        /// </summary>
        public static string m9_2 {
            get {
                return ResourceManager.GetString("m9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to work in Moscow.
        /// </summary>
        public static string m9_3 {
            get {
                return ResourceManager.GetString("m9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading with Moscow.
        /// </summary>
        public static string m9_4 {
            get {
                return ResourceManager.GetString("m9_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up and venture.
        /// </summary>
        public static string m9_5 {
            get {
                return ResourceManager.GetString("m9_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trends.
        /// </summary>
        public static string m9_6 {
            get {
                return ResourceManager.GetString("m9_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        public static string m9_7 {
            get {
                return ResourceManager.GetString("m9_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We simulate situations.
        /// </summary>
        public static string m9_8 {
            get {
                return ResourceManager.GetString("m9_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expositions.
        /// </summary>
        public static string m9_9 {
            get {
                return ResourceManager.GetString("m9_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string magazine {
            get {
                return ResourceManager.GetString("magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the internet connection.
        /// </summary>
        public static string mail_ex {
            get {
                return ResourceManager.GetString("mail_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice businessman.
        /// </summary>
        public static string novice_businessman {
            get {
                return ResourceManager.GetString("novice_businessman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know more.
        /// </summary>
        public static string SendPageText {
            get {
                return ResourceManager.GetString("SendPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to start a business in Moscow? Where to find the financing for it?.
        /// </summary>
        public static string t1 {
            get {
                return ResourceManager.GetString("t1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to rent an office or land lot in Moscow?.
        /// </summary>
        public static string t2 {
            get {
                return ResourceManager.GetString("t2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to localize your production in Moscow?.
        /// </summary>
        public static string t3 {
            get {
                return ResourceManager.GetString("t3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytical data and economic indicators..
        /// </summary>
        public static string t4 {
            get {
                return ResourceManager.GetString("t4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success stories of foreign businessmen in Moscow..
        /// </summary>
        public static string t5 {
            get {
                return ResourceManager.GetString("t5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success stories of foreign businessmen in Moscow..
        /// </summary>
        public static string t6 {
            get {
                return ResourceManager.GetString("t6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBack.
        /// </summary>
        public static string TextBlockFeedBack {
            get {
                return ResourceManager.GetString("TextBlockFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which topics would you like to see covered in our magazine?.
        /// </summary>
        public static string topic {
            get {
                return ResourceManager.GetString("topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industial Automation.
        /// </summary>
        public static string v1 {
            get {
                return ResourceManager.GetString("v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion&amp;Automation.
        /// </summary>
        public static string v2 {
            get {
                return ResourceManager.GetString("v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital factory.
        /// </summary>
        public static string v3 {
            get {
                return ResourceManager.GetString("v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string v4 {
            get {
                return ResourceManager.GetString("v4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industial Supply.
        /// </summary>
        public static string v5 {
            get {
                return ResourceManager.GetString("v5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Business&amp;Markets.
        /// </summary>
        public static string v6 {
            get {
                return ResourceManager.GetString("v6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research&amp;Technology.
        /// </summary>
        public static string v7 {
            get {
                return ResourceManager.GetString("v7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all the questions.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are.
        /// </summary>
        public static string You_are {
            get {
                return ResourceManager.GetString("You_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business sector.
        /// </summary>
        public static string Your_business_sector {
            get {
                return ResourceManager.GetString("Your_business_sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your country:.
        /// </summary>
        public static string Your_country {
            get {
                return ResourceManager.GetString("Your_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your question:.
        /// </summary>
        public static string Your_q {
            get {
                return ResourceManager.GetString("Your_q", resourceCulture);
            }
        }
    }
}
